---
- name: Converge
  hosts: all
  become: yes
  vars:
    rke2_version: v1.21.6+rke2r1
    rke2_ha_mode: true
    rke2_server_taint: true
    rke2_api_ip: 192.168.123.100
    rke2_snapshooter: native
  roles:
     - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
