---
- name: Download RKE2 kubeconfig to localhost
  ansible.builtin.fetch:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
    flat: yes
  when:
  - rke2_download_kubeconf | bool
  - inventory_hostname == groups[rke2_servers_group_name].0

- name: Replace loopback IP by master server IP
  ansible.builtin.replace:
    path: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
    mode: '0600'
    regexp: '127\.0\.0\.1|\[::1\]'
    replace: "{{ rke2_api_ip | default(hostvars[groups[rke2_servers_group_name].0].ansible_host) | ansible.utils.ipwrap }}"
  delegate_to: localhost
  become: false
  when:
  - not ansible_check_mode
  - rke2_download_kubeconf | bool
  - inventory_hostname == groups[rke2_servers_group_name].0
