---

- name: Populate services facts
  ansible.builtin.service_facts:
  # gathering service facts can be slow, only do so after install / upgrade
  when: rke2_version != installed_version

- name: Set the Active Server variable
  ansible.builtin.set_fact:
    active_server: "{{ inventory_hostname }}"
  delegate_facts: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups[rke2_cluster_group_name] }}"
  when:
    - inventory_hostname in groups[rke2_servers_group_name]
    - ansible_facts.services["rke2-server.service"].state == "running"
