---
name: Bug report
description: File a bug report
title: "bug: "
labels: bug

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a bug!**

      Verify first that your issue is not [already reported on
      GitHub][issue search].

      Also test if the latest release is affected too.

- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
    placeholder: >-
      When I try to do X with teraform module from the main branch on GitHub, Y
      breaks in a way Z under the env E. Here are all the details I know
      about this problem...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    description: >
      Please select the single available option in the drop-down.

      <details>
        <summary>
          <em>Why?</em>
        </summary>

        We would do it by ourselves but unfortunately, the current
        edition of GitHub Issue Forms Alpha does not support this yet 🤷


        _We will make it easier in the future, once GitHub
        supports dropdown defaults. Promise!_

      </details>
    options:
    - Bug Report
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible Version
    description: >-
      Paste verbatim output from `ansible --version` below, under
      the prompt line. Please don't wrap it with triple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    placeholder: |
      ansible [core 2.12.5]
        config file = None
        configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
        ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
        ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
        executable location = /home/user/.local/bin/ansible
        python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
        jinja version = 3.0.3
        libyaml = True
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Describe exactly how to reproduce the problem, using a minimal test-case.

      **HINT:** You can paste https://gist.github.com links for larger files.
    value: |
      <!--- Paste example playbook between quotes below -->
      ```yaml (paste below)

      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Results
    description: >-
      Describe what you expected to happen when running the steps above.
    placeholder: >-
      I expected X to happen because I assumed Y.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Results
    description: |
      Describe what actually happened.

      Paste command output and don't wrap it with triple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    placeholder: Ansible command output...
  validations:
    required: true
