---
- name: Converge
  hosts: all
  become: yes
  vars:
    rke2_version: v1.21.6+rke2r1
    rke2_snapshooter: native
  roles:
     - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
