---
- name: Converge
  hosts: all
  become: yes
  vars:
    rke2_version: v1.22.12+rke2r1
    rke2_snapshooter: native
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
